"""Generate SQL tool."""

import logging
from typing import Any

from mcp.protocol import text_content, create_tool_result
from .context import get_context, set_context, get_database_id

logger = logging.getLogger(__name__)


def generate_sql(
    arguments: dict,
    tenant_id: str,
    user_id: str,
) -> dict[str, Any]:
    """
    Generate SQL based on natural language question and RAG context.

    This tool prepares the context for SQL generation. The actual SQL
    should be generated by the LLM based on the returned context.
    """
    question = arguments.get("question", "")
    database_name = arguments.get("database")

    if not question:
        return create_tool_result(
            [text_content("Error: question is required")],
            is_error=True,
        )

    # Get RAG context from previous search
    rag_context = get_context("rag_context")

    if not rag_context:
        return create_tool_result([
            text_content(
                "Warning: No context available. Call search_database_context first "
                "to retrieve relevant schema and examples.\n\n"
                "Proceeding without context - SQL generation may be less accurate."
            )
        ])

    # Get or resolve database ID
    database_id = get_context("database_id")
    if not database_id:
        database_id = get_database_id(tenant_id, database_name)
        if database_id:
            set_context("database_id", database_id)

    # Mark that SQL generation was requested
    set_context("sql_generation_requested", True)

    # Build the SQL generation prompt
    prompt_parts = [
        "Based on the following database context, generate a SQL query to answer this question:",
        f"\n**Question:** {question}\n",
    ]

    # Add context if available
    if rag_context:
        prompt_parts.append("\n---\n")
        prompt_parts.append(rag_context.to_prompt_sections())

    # Add SQL generation guidelines
    prompt_parts.append("""

---

## SQL Generation Guidelines

1. Use only tables and columns that appear in the schema above
2. Follow the patterns shown in the example queries
3. Be mindful of data types and use appropriate functions
4. Limit results if not specified (e.g., LIMIT 100)
5. Use clear column aliases for calculated fields
6. Consider NULL handling where appropriate

Please generate the SQL query now. After reviewing, use execute_sql to run it.
""")

    return create_tool_result([
        text_content("".join(prompt_parts))
    ])
